### PR TITLE
THY-69 setup firebase

### PR DESCRIPTION
**Pull request by kadenbking**
I learned of a problem in the `cwackerfuss` repo when learning more about `.env` variables. I'll look forward to explaining on Monday.

### CODE REVIEW

**Comment by djyarnell0** [comment]
Should I wait to merge this in light of the .env stuff @kadenbking ?

**Comment by kadenbking** [comment]
Yeah let's hold off on reviewing until we can discuss these changes. Thanks for asking @djyarnell0

**Comment by djyarnell0** [comment]
Sounds good! other than that looks great to me

**Review by djyarnell0 — APPROVED** [review]
LGTM

**Pull request merged**
