### PR TITLE
THY-72-75 login profile UI

### PR DESCRIPTION
**Pull request by kadenbking**
This includes a lot of the frontend and should be a good template to work off of @djyarnell0

### CODE REVIEW

**Comment by kadenbking** [comment]
This should be most all of the fronend work complete. The couple of changes still needed are:
- validation on forms before you can click submit
- Stats display on the profile page when a user is signed in

**Comment by kadenbking** [comment]
@kenancasey Part of me wishes we were meeting tomorrow, because I'm really proud of this PR and consider it to be some of my best react work yet. I'm glad we split UI from functionality because this ended up being A LOT of work (as this screenshot from this PR should suggest):
Screenshot 2023-04-13 at 7 33 49 PM

If you review the files changed, you'll notice I've added a lot of components. This work contains a lot of conditional displays that change based on if a user is signed in or not. This should be a great template to work off of @djyarnell0 — I've covered just about every possible situation from a UI standpoint I could think of. There will be very minor changes to some of this when we add functionality — but they will be very minor and I'm happy to help you with any questions you have about that.

I would love to demo this to you both, but in the meantime, I invite you to check out the deploy preview above to view the sign-in / create account form that doesn't work yet. If you pull this branch on your machine, make the following change on line 32 of `SignInTabs.tsx`:

```
if (true) { // changed from `user`
    return (
      <ProfileInformation
        handleLogOut={handleLogOut}
        handleEditProfile={handleEditProfile}
      />
    )
  }
``` 

This will allow you to view the profile page from the perspective of a user who is signed in. This triple if seen in this component is the standard practice of using `useAuthState` from: https://github.com/CSFrequency/react-firebase-hooks

@djyarnell0 I think that repo will provide several bits as you work on functionality. I think that's all for now, thanks for coming to my TED talk.

**Comment by kenancasey** [comment]
@kadenbking I'm available tomorrow and would love to hear what you've done and how you've done it. Are you up for coming and sharing?

**Comment by kadenbking** [comment]
@kenancasey It will depend on my work schedule in the afternoon, I will let you know tomorrow if I can make it.

**Comment by kenancasey** [comment]
@kadenbking I'll be there either way. Let me know what time you plan to be there if you decide to come.

**Comment by djyarnell0** [comment]
@kadenbking I'd like to thank you for showing me your work tonight and commend you for a job well done! You did a great job walking me through everything and i am excited to start linking it all together.

**Review by kenancasey — APPROVED** [review]
Nice work @kadenbking!

**Pull request merged**
